FROM golang:alpine AS build

WORKDIR /opt
RUN apk add git make
RUN go install github.com/shadowsocks/go-shadowsocks2@latest


# Final Docker image 
FROM alpine:latest

RUN apk upgrade \
    && apk add tzdata \
    && rm -rf /var/cache/apk/*

ENV SERVER_IP     0.0.0.0
ENV SERVER_PORT   8399
ENV ENCRYPTION    AEAD_CHACHA20_POLY1305
ENV PASSWORD      $PASSWORD

EXPOSE 8399

WORKDIR /app
COPY --from=build /go/bin/go-shadowsocks2 /app/shadowsocks-server
COPY scripts/entrypoint-shadowsocks-server.sh /app/entrypoint.sh
RUN chmod +x shadowsocks-server entrypoint.sh

VOLUME /app

ENTRYPOINT [ "./entrypoint.sh" ]
