FROM golang:1.17.9-alpine3.15 AS build

WORKDIR /opt
# Install Prerequisites
RUN apk add git make

# Clone Repo
RUN git clone https://github.com/cbeuw/Cloak

# Build application
WORKDIR /opt/Cloak
RUN go get ./...
RUN make

# Final Docker image 
FROM alpine:latest

RUN apk upgrade \
    && apk add tzdata libqrencode \
    && rm -rf /var/cache/apk/*
    
ENV LOCAL_IP     127.0.0.1
ENV LOCAL_PORT   8399
ENV METHOD       shadowsocks
ENV BYPASSUID    null
ENV REDIRADDR    1.0.0.1
ENV PRIVATEKEY   null
ENV ADMINUID     null 
ENV PUBLICKEY    null
ENV ENCRYPTION   AEAD_CHACHA20_POLY1305
ENV PASSWORD     null

WORKDIR /app
COPY --from=build /opt/Cloak/build/ck-server /app/ck-server
COPY config/cloak-server.conf /app/config.json
COPY scripts/entrypoint-cloak-server.sh /app/entrypoint.sh
RUN chmod +x ck-server
RUN chmod +x entrypoint.sh

ENTRYPOINT [ "./entrypoint.sh" ]
CMD [ "/app/ck-server" , "-c" , "/app/config.json" ]
