FROM golang:latest

WORKDIR /opt
RUN git pull https://github.com/cbeuw/Cloak.git
RUN go get github.com/boltdb/bolt & \
    go get github.com/juju/ratelimit & \
    go get github.com/gorilla/mux & \
    go get github.com/gorilla/websocket & \
    go get github.com/sirupsen/logrus & \
    go get golang.org/x/crypto & \
    go get github.com/refraction-networking/utls

RUN make server